DROP TABLE IF EXISTS CREDIT_CARD_DATA;
CREATE TABLE CREDIT_CARD_DATA (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CARD_NUMBER VARCHAR(19) NOT NULL,
    CUST_NAME VARCHAR(255) NOT NULL,
    CREDIT_LIMIT DOUBLE NOT NULL,
	BALANCE DOUBLE NOT NULL
   
);